# Generated by Django 3.2.2 on 2021-05-08 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gui.member'),
        ),
    ]
