# Generated by Django 3.2.2 on 2021-05-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_family_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='responsable',
        ),
        migrations.AddField(
            model_name='member',
            name='est_responsable',
            field=models.BooleanField(default=False),
        ),
    ]
