# Generated by Django 3.2.2 on 2021-05-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20210508_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='gui.famille'),
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200)),
                ('convention', models.BooleanField(default=False)),
                ('capacite', models.IntegerField(default=2)),
                ('disponible', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='gui.hotel')),
            ],
        ),
    ]
