# Generated by Django 3.2.2 on 2021-05-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_auto_20210508_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PEC', to='gui.famille')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='PEC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chambres', to='gui.pec'),
        ),
    ]
