# Generated by Django 3.2.2 on 2021-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_auto_20210508_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='famille',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='pec',
            options={'ordering': ['date_fin']},
        ),
        migrations.AddField(
            model_name='chambre',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexe',
            field=models.IntegerField(choices=[(0, 'Autre'), (1, 'Masculin'), (2, 'Féminin')], default=0),
        ),
    ]
